// To-do not make it case sensitive

String getCommodityImage(String commodityName, {String? commodityType, String? specification}) {
  // Map commodity names and types to their corresponding image file names
  final Map<String, String> imageMap = {
    "Ampalaya": "ampalaya.jpg",
    "Avocado": "avocado.jpg",
    "Banana (Lakatan)": "banana_lakatan.png",
    "Banana (Latundan)": "banana_latundan.jpg",
    "Banana (Saba)": "banana_saba.jpg",
    "Bangus": "bangus.jpg",
    "Beef Rump": "beef_rump.jpg",
    "Beef Brisket": "beef_brisket.jpg",
    "Bell Pepper (Green)": "bell_pepper_green.jpg",
    "Bell Pepper (Red)": "bell_pepper_red.jpg",
    "Bonito": "bonito.jpg",
    "Broccoli": "broccoli.jpg",
    "Cabbage (Rare Ball)": "cabbage_rare_ball.jpg",
    "Cabbage (Scorpio)": "cabbage_scorpio.jpg",
    "Cabbage (Wonder Ball)": "cabbage_wonder_ball.jpg",
    "Calamansi": "calamansi.jpg",
    "Carrots": "carrot.jpg",
    "Cauliflower": "cauliflower.jpg",
    "Celery": "celery.jpg",
    "Chayote": "chayote.jpg",
    "Chicken Egg (White, Pewee)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Extra Small)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Small)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Medium)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Large)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Extra Large)": "chicken_egg_white.jpg",
    "Chicken Egg (White, Jumbo)": "chicken_egg_white.jpg",
    "Chicken Egg (Brown, Medium)": "chicken_egg_brown.jpg", 
    "Chicken Egg (Brown, Large)": "chicken_egg_brown.jpg", 
    "Chicken Egg (Brown, Extra Large)": "chicken_egg_brown.jpg", 
    "Chili (Red)": "chilli_red.jpg",
    "Cooking Oil (Coconut)": "cooking_oil_coconut.png",
    "Cooking Oil (Palm)": "cooking_oil_palm.jpg",
    "Corn (Cracked)": "corn_cracked.jpg",
    "Corn Grits": "corn_grits.jpg",
    "Eggplant": "eggplant.jpg",
    "Frozen Liempo": "frozen_liempo.jpg",
    "Galunggong (Local)": "galunggong.jpg",
    "Galunggong (Imported)": "galunggong.jpg",
    "Garlic": "garlic.jpg",
    "Ginger": "ginger.jpg",
    "Habi chuelas (Baguio Beans)": "habichuelas.jpg",
    "Well milled": commodityType == "Kadiwa Rice-for-all"
    ? "kadiwariceforall_rice.jpg"
    : commodityType == "Imported Commercial Rice"
        ? "imported_commercial_rice.jpg"
        : "local_commerce_rice.jpg",
    "Special": commodityType == "Imported Commercial Rice" ? "imported_commercial_rice.jpg" : "local_commerce_rice",
    "Premium": commodityType == "Imported Commercial Rice" ? "imported_commercial_rice.jpg" : "local_commerce_rice",
    "Regular milled": commodityType == "Imported Commercial Rice" ? "imported_commercial_rice.jpg" : "local_commerce_rice",
    "Kadiwa Rice-for-all": "kadiwariceforall_rice.jpg",
    "Lettuce (Green Ice)": "lettuce_green_ice.jpg",
    "Lettuce (Iceberg)": "lettuce_iceberg.jpg",
    "Lettuce (Romaine)": "lettuce_romaine.jpg",
    "Local Commercial Rice": "local_commerce_rice.jpg",
    "Mango (Carabao)": "mango_carabao.jpg",
    "Melon": "melon.jpg",
    "Papaya": "papaya.jpg",
    "Pechay": "pechay.jpg",
    "Pomelo": "pomelo.jpg",
    "Pork Belly": "pork_belly.jpg",
    "Pork Ham": "pork_ham.jpg",
    "Red Onion": "red_onion.jpg",
    "Salmon Head": "salmon_head.jpg",
    "Sardines (Tamban)": "sardines.jpg",
    "Sitao": "sitao.jpg",
    "Squash": "squash.jpg",
    "Squid (Pusit Bisaya)": "squids.jpg",
    "Sugar (Brown)": "sugar_brown.jpg",
    "Sugar (Refined)": "sugar_refined.jpg",
    "Sugar (Washed)": "sugar_washed.jpg",
    "Tilapia": "tilapia.jpg",
    "Tomato": "tomato.jpg",
    "Watermelon": "watermelon.jpg",
    "Corn (White)": "white_corn.jpg",
    "White Onion": "white_onion.jpg",
    "White Potato": "white_potato.jpg",
    "Whole Chicken": "whole_chicken.jpg",
    "Corn (Yellow)": "yellow_corn.jpg",
    "Yellow-Fin Tuna (Tambakal)": "yellow_fin_tuna.jpg",
    "Alumahan": "alumahan.jpg",
  };

  // Return the image path if found, otherwise return a default image
  return imageMap[commodityName] ?? "default_image.jpg";
}